name: takeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.4
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logos/Asteri.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFBF5"
  adaptive_icon_foreground: "assets/Logos/Asteri.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/Logos/
  
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/Fonts/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/Fonts/Quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Quicksand/static/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
    
    - family: Figtree
      fonts:
        - asset: assets/Fonts/Figtree/static/Figtree-Light.ttf
          weight: 300
        - asset: assets/Fonts/Figtree/static/Figtree-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Figtree/static/Figtree-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Figtree/static/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Figtree/static/Figtree-Bold.ttf
          weight: 700